### ISSUE TITLE
Issue With Non-Haskell Code Formatting In Part 2

### ISSUE THREAD

**Issue by Shamrock-Frost** [rcook/beginning-practical-haskell#1]
The MathJax (at least I think it's MathJax) is broken in Part 2. 
![Image from my screen](https://cloud.githubusercontent.com/assets/6888761/20865204/c0d89230-b9c0-11e6-9091-d60e58249d56.png)

**Comment by rcook** [comment]
Thanks! I'll take a look. Is it broken just in GitHub or in Pandoc? What you see in GitHub is just an approximation of how the Markdown is rendered by Pandoc. GFM doesn't support MathJax, for example.

**Comment by rcook** [comment]
I've just verified that the output generated by Pandoc is correct. As stated above, GitHub only provides an approximation of the intended output. I'll add a comment in the `README.md` to this effect.
